# Site settings
title: Ranger_Ray
email: zhourui86525@163.com
description: > # this means to ignore newlines until "baseurl:"
  this site is used to record and share it with others 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  ray525
timezone: Asia/Shanghai
# Build settings
markdown: kramdown
highlighter: pygments